on: [push]
jobs:
  generate-doc:
    runs-on: ubuntu-latest
    name: Generate documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout googleapis
        uses: actions/checkout@v2
        with:
          repository: googleapis/googleapis
          path: _deps/googleapis
      - name: Generate documentation
        uses: LedgerHQ/proto-gendoc-action@v1
        with:
          api-name: Bitcoin Keychain
          api-version: 1.0.0
          proto-root-dir: pb
          proto-include-dir: _deps/googleapis
      - name: Publish documentation
        run: npx @redocly/openapi-cli@latest push [openapi.yaml] "@ledger/bitcoin-keychain-proto@v1"
