name: Generate documentation
on:
  push:

jobs:
  generate_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: generate png diagrams
        uses: Timmy/plantuml-action@v1
        with:
          args: "-tpng doc/*.puml"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install buf
        uses: bufbuild/buf-setup-action@v0.7.0
        with:
          version: '1.0.0-rc3'

      - name: generate swagger
        uses: magefile/mage-action@v1
        with:
          args: -v proto

      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[bot] update documentation"
          file_pattern: "doc/*.png pb/*/*.swagger.json"
