name: Build and Test
on:
  pull_request:
    branches:
      - main
      - 'release/*'
  push:
    branches:
      - '*'
jobs:
  go:
    name: Go CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Protobuf compiler
        uses: arduino/setup-protoc@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1.1.0
        with:
          version: '1.0.0-rc3'

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1

      - name: Run Buf checks
        uses: magefile/mage-action@v1
        with:
          args: -v buf

      - name: Build
        uses: magefile/mage-action@v1
        with:
          args: -v build

      - name: Run code linting
        uses: magefile/mage-action@v1
        with:
          args: -v lint

      - name: Test (with -race flag)
        uses: magefile/mage-action@v1
        with:
          args: -v testracecover

      - name: Code coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
