name: Integration tests
on:
  pull_request:
    branches:
      - main
      - 'release/*'
  push:
    branches:
      - '*'
jobs:
  integration:
    name: Integration CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Protobuf compiler
        uses: arduino/setup-protoc@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install buf
        uses: bufbuild/buf-setup-action@v0.7.0
        with:
          version: '1.0.0-rc3'

      - name: Install Protobuf Go plugin
        run: go get github.com/golang/protobuf/protoc-gen-go

      - name: Check out bitcoin-lib-grpc
        uses: actions/checkout@v3
        with:
          repository: LedgerHQ/bitcoin-lib-grpc
          path: 'bitcoin-lib-grpc'

      - name: Build bitcoin-lib-grpc
        uses: magefile/mage-action@v1
        with:
          workdir: bitcoin-lib-grpc
          args: -v build

      - name: Run bitcoin-lib-grpc in the background
        working-directory: bitcoin-lib-grpc
        run: ./lbs &

      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0

      - name: Run Buf checks
        uses: magefile/mage-action@v1
        with:
          args: -v proto

      - name: Run integration tests
        uses: magefile/mage-action@v1
        with:
          args: -v integration
